{{- if not .Values.mysql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-spotguide.fullname" . }}-cluster
  labels:
    app.kubernetes.io/name: {{ include "mysql-spotguide.name" . }}
    helm.sh/chart: {{ include "mysql-spotguide.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ROOT_PASSWORD: {{ default (derivePassword 1 "long" "root" .Release.Name .Chart.Name ) .Values.mysql.rootPassword | b64enc | quote }}
  USER: {{ default (derivePassword 1 "long" "user" .Release.Name .Chart.Name ) .Values.mysql.user | b64enc | quote }}
  PASSWORD: {{ default (derivePassword 1 "long" "password" .Release.Name .Chart.Name ) .Values.mysql.password | b64enc | quote }}
{{- end }}
