{{ if and .Values.phpmyadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql-spotguide.fullname" . }}-phpmyadmin
  labels:
    app.kubernetes.io/name: {{ include "mysql-spotguide.name" . }}
    helm.sh/chart: {{ include "mysql-spotguide.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.phpmyadmin.service.type }}
  ports:
    - name: http
      port: {{ .Values.phpmyadmin.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mysql-spotguide.name" . }}
    helm.sh/chart: {{ include "mysql-spotguide.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{ end }}
