{{ if and .Values.phpmyadmin.enabled (not .Values.phpmyadmin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql-spotguide.fullname" . }}-phpmyadmin
  labels:
    app.kubernetes.io/name: {{ include "mysql-spotguide.name" . }}
    helm.sh/chart: {{ include "mysql-spotguide.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{ default "control_user" .Values.phpmyadmin.control_user | b64enc | quote }}
  password: {{ default (derivePassword 1 "long" (.Release.Time | toString) .Release.Name .Chart.Name ) .Values.phpmyadmin.control_password | b64enc | quote }}
{{ end }}
