{{ if .Values.phpmyadmin.enabled }}
{{- if and .Values.phpmyadmin.ingress.enabled (gt (len .Values.phpmyadmin.ingress.hosts) 0) -}}
{{- $serviceName := include "mysql-spotguide.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "mysql-spotguide.fullname" . }}-phpmyadmin
  labels:
    app.kubernetes.io/name: {{ include "mysql-spotguide.name" . }}
    helm.sh/chart: {{ include "mysql-spotguide.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.phpmyadmin.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.phpmyadmin.ingress.tls }}
  tls:
  {{- range .Values.phpmyadmin.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.phpmyadmin.ingress.hosts }}
  {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
          - path: /{{ rest $url | join "/" }}
            backend:
              serviceName: {{ $serviceName }}-phpmyadmin
              servicePort: http
  {{- end}}
{{- end }}
{{- end }}
